{
 "title": "Base Monitoring",
 "time": { "from": "2025-06-01T22:00:00.000Z", "to": "2025-06-27T21:59:59.000Z" },
 "panels": [
  {
   "title": "# Tickers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(num_tickers), MAX(num_tickers) FROM evidently_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM evidently_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "# Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM evidently_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM evidently_metrics LIMIT 50 "
    }
   ]
  }
 ]
}