name: CD Deploy
on:
  push:
    branches:
      - dev
      - prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}
      PROJECT_ID: stocks-forecasting-466906
      REGION: europe-west1
      REPO: stocks-forecasting-repo
      IMAGE_NAME: stocks_forecasting_inference
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      VERSION: latest
      SERVICE_NAME_ROOT: stocks-forecasting-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1: define derived variables and emit as outputs
      - name: Set derived variables
        id: vars
        run: |
          # determine simplified branch name (test, dev, prod)
          if [[ "${GITHUB_REF_NAME}" == "dev" || "${GITHUB_REF_NAME}" == "prod" ]]; then
            BRANCH_SIMPLE="${GITHUB_REF_NAME}"
          else
            BRANCH_SIMPLE="test"
          fi
          echo "image uri and service name will be suffixed with ${BRANCH_SIMPLE}"

          # compute image URI and service name
          image_uri="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/${IMAGE_NAME}:${VERSION}-${BRANCH_SIMPLE}"
          service_name="${SERVICE_NAME_ROOT}-${BRANCH_SIMPLE}"

          # emit to GitHub Actions
          echo "branch_simple=${BRANCH_SIMPLE}"   >> $GITHUB_OUTPUT
          echo "image_uri=${image_uri}"           >> $GITHUB_OUTPUT
          echo "service_name=${service_name}"     >> $GITHUB_OUTPUT

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"
          enable-cache: true

      - name: Install dependencies
        run: |
            uv sync --locked --all-extras --dev
            uv pip install -e .

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Download extracted model"
        run: |
          echo "Downloading extracted model from GCS bucket: ${{ steps.vars.outputs.branch_simple }}"
          uv run python scripts/download_extracted_model_from_cloud.py --env ${{ steps.vars.outputs.branch_simple }} --refresh

      - name: Build the image
        run: |
          echo "Building image_uri:tag ${{ steps.vars.outputs.image_uri }}"
          docker build -f Docker/Dockerfile -t ${{ steps.vars.outputs.image_uri }} .

      - name: Configure Docker to use GAR
        run: |
          echo "Configuring Docker to auth with GAR"
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

      - name: Tag and push images to GAR
        run: |
            echo "Pushing Docker image to GAR: ${{ steps.vars.outputs.image_uri }}"
            docker push ${{ steps.vars.outputs.image_uri }}

      - name: Deploy the GAR image to Cloud Run
        run: |
            SERVICE_ACCOUNT="stocks-forecasting-mle@${PROJECT_ID}.iam.gserviceaccount.com"
            echo "Deploying ${IMAGE_URI} to Cloud Run"
            gcloud run deploy ${{ steps.vars.outputs.service_name }} \
            --image=${{ steps.vars.outputs.image_uri }} \
            --region=${REGION} \
            --platform=managed \
            --project=${PROJECT_ID} \
            --service-account=${SERVICE_ACCOUNT} \
            --allow-unauthenticated \
            --port=9696
